### ISSUE TITLE
Enkapsulacja

### ISSUE THREAD

**Issue by TomaszZupka** [robertkonior/Robert-Konior-kodilla-java#1]
Warto zwiększyć enkapsulację klasy poprzez odpowiedni modyfikator

https://github.com/robertkonior/Robert-Konior-kodilla-java/blob/7aa2ccf1c58d5aaa60db50413da28a1be78a61bd/kodilla-testing/src/main/java/com/kodilla/testing/shape/ShapeCollector.java#L4

**Comment by robertkonior** [comment]
tak ?
 private List<Shape> figureList =new ArrayList<Shape>();
