### ISSUE TITLE
Zmienna instancyjna

### ISSUE THREAD

**Issue by TomaszZupka** [robertkonior/Robert-Konior-kodilla-java#2]
To spokojnie może być zmienna instancyjna

https://github.com/robertkonior/Robert-Konior-kodilla-java/blob/7aa2ccf1c58d5aaa60db50413da28a1be78a61bd/kodilla-testing/src/main/java/com/kodilla/testing/shape/ShapeCollector.java#L5

**Comment by robertkonior** [comment]
czyli zmienna zdeklarowana w metodzie
